
import frappe
import time

@frappe.whitelist()
def generate_faqs(doctype, docname):
    """
    Generate FAQs for a single Web Page or Blog Post.
    This function is called from the button in the form.
    """
    ai_agent_name = "FAQs Agent"
    if not frappe.db.exists("AI Agent", ai_agent_name):
        frappe.throw(f"AI Agent '{ai_agent_name}' does not exist.")

    ai_agent_doc = frappe.get_doc("AI Agent", ai_agent_name)
    agent_service = ai_agent_doc.agent_service
    if not agent_service:
        frappe.throw(f"AI Agent '{ai_agent_name}' has no configured service.")

    # Fetch the document
    doc = frappe.get_doc(doctype, docname)
    if not doc.published:
        frappe.throw(f"{doctype} '{docname}' is not published.")

    # Build full URL
    doc_route = doc.route or ""
    full_url = f"https://finbyz.tech/{doc_route}"

    result = agent_service.invoke(url=full_url)
    if not result:
        frappe.throw("AI agent returned an empty result.")
    doc.faqs = []
    for faq in result.faqs:
        question = faq.question
        answer = faq.answer
        if question and answer:
            doc.append("faqs", {"question": question, "answer": answer})

    if not doc.faqs:
        frappe.throw("No valid FAQs were generated by the AI.")

    doc.save()
    faq_count = len(doc.faqs)
    
    frappe.msgprint(
        msg=f"Successfully generated {faq_count} FAQs for '{doc.title}'",
        title="FAQ Generation Complete", 
        indicator="green"
    )
    
    return {
        "success": True,
        "message": "FAQ generation completed",
        "doctype": doctype,
        "docname": doc.name,
        "title": doc.title,
        "faq_count": faq_count
    }


def generate_faqs_bulk(doctype, docnames):		
    results = {
        "success": [],
        "failed": [],
        "skipped": []
    }
    
    for docname in docnames:
        try:				
            if not frappe.db.exists(doctype, docname):
                results["skipped"].append({
                    "docname": docname,
                    "reason": "Document not found"
                })
                continue
            
            result = generate_faqs(doctype, docname)
            
            if result.get("success"):
                results["success"].append({
                    "docname": docname,
                    "title": result.get("title"),
                    "faq_count": result.get("faq_count")
                })
            else:
                results["failed"].append({
                    "docname": docname,
                    "error": result.get("message")
                })
        except Exception as e:
            error_msg = str(e)
            frappe.logger().error(f"[FAQ Bulk] Error processing {docname}: {error_msg}")
            results["failed"].append({
                "docname": docname,
                "error": error_msg
            })
        time.sleep(60)
    return results


@frappe.whitelist()
def create_faqs_for_documents(doctype, docnames):
    """
    Generate FAQs for multiple Web Pages or Blog Posts.
    
    Args:
        doctype (str): "Web Page" or "Blog Post"
        docnames (str or list): JSON string or list of document names
    """
    if doctype not in ['Web Page','Blog Post','Gallery']:
        frappe.throw(f"{doctype} not allowed to generate faqs")
  
    if isinstance(docnames, str):
        docnames = frappe.parse_json(docnames)
    
    if not isinstance(docnames, list):
        frappe.throw("docnames must be a list of document names")
    
    if not docnames:
        frappe.throw("No documents provided for bulk generation")
    
    job = frappe.enqueue(generate_faqs_bulk, doctype = doctype,docnames=docnames,queue='long',job_name=f'faqs generation for {doctype}')
    return {
        "sucess": True,
        'job_id': job.id
    }
